import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReactQueryProvider } from "@/lib/providers/react-query-provider";
import { Suspense } from "react";
import { Loader2 } from "lucide-react";
import Navbar from "@/components/common/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          async
          crossOrigin="anonymous"
          src="//unpkg.com/react-scan/dist/auto.global.js"
        />
      </head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark`}
      >
        <ReactQueryProvider>
          <Suspense
            fallback={
              <div className="h-dvh w-dvw flex items-center justify-center">
                <Loader2 className="h-8 w-8 animate-spin" />
              </div>
            }
          >
            <Navbar />
            {children}
          </Suspense>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
